/*
 * This source file was generated by the Gradle 'init' task
 */
package com.assignment.gateway;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApiGatewayApplicationTest {
    @Test void appHasAGreeting() {
        ApiGatewayApplication classUnderTest = new ApiGatewayApplication();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
